name: My_Github_Actions_Basics
env:
  APPLICATION_NAME: 'MyApp'
  VERSION: 'ver ${{ github.sha }}'

on:
  push:
    branches:
      - main

jobs:
  my_testing:
    runs-on:  ubuntu-latest
    steps:
    - name: Print Hello Message
      run : echo "Hello World from Testing"

    - name: Execute few commands
      run : |
        echo "Hello Message1"
        echo "Hello Message2"
        echo "Application name: ${{ env.APPLICATION_NAME }}"

    - name: List current folder
      run : ls -la

    - name: Git clone my repo
      uses: action/checkout@v1

    - name: List current folder
      run : ls -la


  my_deploy:
    runs-on: ubuntu-latest
    needs: [my_testing]
    steps:
    - name: Print Hello Message
      run : echo "Hello World from Deploy"

    - name: Printing Deployment Package
      run : |
        echo "Hello Message1"
        echo "Hello Message2"
        echo "Application name: ${{ env.VERSION }}"

    - name: Lets test
      run : ps -ef
